### PR TITLE
Improved Server interaction

### PR DESCRIPTION
**Pull request by tdcornish**
Server class has both get matches and get messages working, send message is close to working if I can figure out why it won't POST.

### CODE REVIEW

**Comment by jmhwang7** [comment]
This looks awesome. I like the move to HttpUrlConnection and the gson SerializedName annotations. Only things I would change (feel free to make any or none of these):
1. Is `MessageJson` a duplicate class?
2. I changed the original field names of `Message.java` to match the server because I didn't know about `SerializedName`, but I think it's better to use `SerializedName` like you did in `Match.java`. So maybe change it back to the original names and add the annotation?
3. In the `build...Url` functions, maybe do the URL building like how I did it? I think it's a little better than just string concatenation, and it'll get rid of the `throws MalformedUrlException`. 
Overall, pretty awesome.

**Comment by buildist** [comment]
Haven't used Gson but the code looks good. It might be a good idea to simplify the code for building the request, since right now adding a new API call would require adding a constant, 2 methods and a line to a switch statement. Maybe replace the params array with a key/value map, so it would be easy to convert it to a list of parameters that could either be appended to the URL for GET or put in the body for POST, and you wouldn't need as much separate code for every API call..

**Comment by B50calabrese** [comment]
Jacob has a good point, we should do it that way to make it easier in case we need more functionality.

**Comment by tdcornish** [comment]
That's definitely a good idea, can't believe I didn't think of that haha.

1) MessageJson is a duplicate class, I did it to avoid having to mess with the stuff that was using Message. Since you modified the fields, it's a useless class.
2) Yeah I agree
3) So I tried doing it that way using URI because I agree it looks a lot better, but then I found out that would only work on an Android device since the APK jars are just stubs, so I went with string building so I could test it.

**Comment by tdcornish** [comment]
Ok, I made those changes so go ahead and look at them

**Comment by jmhwang7** [comment]
I made a teensy change, but it looks good to me! I'm gonna go ahead and merge it.

**Comment by B50calabrese** [comment]
Awesome, now we have a fresh place to start from tomorrow. See you guys in the CoC tomorrow and we can hammer out some of the details of the implementation.

**Pull request merged**
