### PR TITLE
Added gson dependency. Refactored Message to have same data fields as se...

### PR DESCRIPTION
**Pull request by jmhwang7**
...rver.

### CODE REVIEW

**Comment by jmhwang7** [comment]
I think we might need to refactor `HttpServerCommunication` and have different classes for the each HTTP call. With the current structure, the flow I wanted to do was have `HttpServerCommunication.getMessages()` be called by `ConversationList`, but it's currently hard to access that `ConversationList` and update it with new data in `getMessagesHandle`r.

**Comment by B50calabrese** [comment]
I think all of the changes make sense, and I find nothing wrong with it. I am going to merge the pull request, what do we need to do moving forward? I am guessing that we just need to have it hook in directly with the rest of the app? I am fine with the ConversationList getting the messages, that actually is probably best. We can get this working tomorrow I believe. I might bring an extra test device too so that we can see if we got messaging working correctly.

**Comment by tdcornish** [comment]
I've been refactoring the HTTPServerCommunciation class into a Server class in the messages branch if you want to take a look.

**Comment by B50calabrese** [comment]
That looks like a lot of what we want, is there anyway you can create a pull request for that using the new code?

**Comment by tdcornish** [comment]
Yeah, I'm cleaning the branch up now and merging it with Jennifer's changes and then I'll do a pull.

**Comment by B50calabrese** [comment]
Sweet sounds good.

**Pull request merged**
