### PR TITLE
Conversation list

### PR DESCRIPTION
**Pull request by B50calabrese**
Changed the updating logic of Conversation Lists.

### CODE REVIEW

**Comment by B50calabrese** [comment]
Note there are A LOT of hacks

**Comment by jmhwang7** [comment]
@B50calabrese I changed it to be asynchronous, but it's still hacky. What do you think?

**Comment by B50calabrese** [comment]
I don't see how this couldn't work, but I am just nervous that it won't draw correctly. Let's merge this and from there we can make changes if need be. I want to get profile set up and the MessagesActivity working.

**Comment by jmhwang7** [comment]
Sounds good! I tested it, and it does load the messages correctly (I initially just took out the synchronize stuff and it rendered nothing), but yeah, there might be problems later.

**Comment by B50calabrese** [comment]
I will do some tests tomorrow, ideally I think we need to get the sending of messages working next so that we have some communication to show for our demo.

**Pull request merged**
